version: '3'
services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: mysql.railway.internal
      DB_USER: root
      DB_PASSWORD: MwPvMsPHvPbBPOOBYdhKSVgVMUPndinp
      DB_NAME: railway
      DB_PORT: 3306
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: MwPvMsPHvPbBPOOBYdhKSVgVMUPndinp
      MYSQL_DATABASE: railway
    ports:
      - "3306:3306"
